#!/bin/bash

#修改为自己的api_key
API_KEY='YOUR_API'
#新建vps的机房id
REGION_ID='YOUR_REGION_ID'
#新建vps的套餐种类
PLAN_ID='YOUR_ID'
#新建vps的快照id
SNAPSHOT_ID='YOUR_SNAPSHOT_ID'
#新建vps标签
VPS_LABEL='YOUR_LABEL'

readonly API_KEY
readonly REGION_ID
readonly PLAN_ID
readonly SNAPSHOT_ID
readonly VPS_LABLE

curl -H 'API-Key: '${API_KEY}'' https://api.vultr.com/v1/server/create --data 'DCID='${REGION_ID}'' --data 'VPSPLANID='${PLAN_ID}'' --data 'OSID=164' --data 'SNAPSHOTID='${SNAPSHOT_ID}'' --data 'label='${VPS_LABEL}''
